"""Add BudgetShare model for sharing goals

Revision ID: 37fc2860a451
Revises: dfd4e78d02e3
Create Date: 2025-05-10 15:01:30.554586

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37fc2860a451'
down_revision = 'dfd4e78d02e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('budget_share',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('shared_with_id', sa.Integer(), nullable=False),
    sa.Column('share_date', sa.DateTime(), nullable=True),
    sa.Column('share_budget', sa.Boolean(), nullable=True),
    sa.Column('share_goals', sa.Boolean(), nullable=True),
    sa.Column('share_goal1', sa.Boolean(), nullable=True),
    sa.Column('share_goal2', sa.Boolean(), nullable=True),
    sa.Column('share_goal3', sa.Boolean(), nullable=True),
    sa.Column('message', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['shared_with_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('budget_share')
    # ### end Alembic commands ###
