"""empty message

Revision ID: 5096a599daae
Revises: 2c14a5c8ee83
Create Date: 2025-05-03 13:56:28.903142

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5096a599daae'
down_revision = '2c14a5c8ee83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('financials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userid', sa.Integer(), nullable=False),
    sa.Column('income', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=200), nullable=False),
    sa.Column('food', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('rent', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('utilities', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('shopping', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('entertainment', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('other', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('goal1', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('goal2', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['userid'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userid', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=200), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['userid'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transactions')
    op.drop_table('financials')
    # ### end Alembic commands ###
